name: status_saver
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  awesome_snackbar_content: ^0.1.3
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  device_info_plus: ^10.1.2
  flutter_spinkit: ^5.2.1
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: custom
      fonts:
        - asset: assets/fonts/custom.ttf
    - family: logo_style
      fonts:
        - asset: assets/fonts/logo_style.ttf
